;;; jylhis-catppuccin-latte-theme.el --- Jylhis × Catppuccin Latte (light) -*- lexical-binding: t; -*-
;;
;; HAND-AUTHORED. Not regenerated by `bun scripts/generate.mjs'.
;; Inspired by https://rahuljuliato.com/posts/modus-catppuccin
;;
;; Author:      Markus Jylhänkangas
;; Homepage:    https://jylhis.com
;; Keywords:    faces, theme
;; Package-Requires: ((emacs "28.1"))
;;
;;; Commentary:
;;
;;  Catppuccin "Latte" recoloring of the Jylhis Emacs face map.
;;  Inspired by Rahul Juliato's Modus-Catppuccin write-up, this sibling reuses
;;  the same Modus-style semantic face targeting as `jylhis-paper-theme.el',
;;  but substitutes the palette block with values from the official Catppuccin
;;  Latte flavor (https://catppuccin.com/palette/).  A sibling
;;  `jylhis-catppuccin-mocha-theme.el' ships the dark variant.
;;
;;  Unlike `jylhis-paper-theme.el', this file is hand-authored and does NOT
;;  participate in `bun scripts/generate.mjs'.  It is shipped alongside the
;;  generated Paper/Roast themes as an alternative palette for users who
;;  prefer the Catppuccin look.  The face mapping is otherwise identical to
;;  Paper, so install/toggle behave the same way.
;;
;;  Install:
;;    (add-to-list 'custom-theme-load-path "~/.config/emacs/themes/")
;;    (load-theme 'jylhis-catppuccin-latte t)
;;
;;  Pair with `jylhis-catppuccin-mocha' via auto-dark:
;;    (setq auto-dark-light-theme 'jylhis-catppuccin-latte
;;          auto-dark-dark-theme  'jylhis-catppuccin-mocha)
;;    (auto-dark-mode 1)
;;
;;; Code:

(deftheme jylhis-catppuccin-latte
  "Jylhis × Catppuccin Latte — light theme. Peach accent on Latte base, Modus-style face map with Catppuccin syntax palette.")

(let ((class '((class color) (min-colors 256)))

      ;; ── Core palette (Catppuccin Latte) ──
      (bg            "#eff1f5") ; base
      (bg-subtle     "#e6e9ef") ; mantle
      (surface       "#dce0e8") ; crust
      (surface-raised "#f5f7fa") ; lighter-than-base tint for "raised"
      (fg            "#4c4f69") ; text
      (fg-muted      "#5c5f77") ; subtext1
      (fg-heading    "#3c3f59") ; manual darker text for hierarchy
      (fg-faint      "#8c8fa1") ; overlay1
      (accent        "#fe640b") ; peach — Jylhis copper analogue
      (accent-hover  "#e64553") ; maroon
      (accent-subtle "#ffd9c2") ; peach wash (opaque approximation)
      (brand         "#fe640b") ; peach
      (border        "#9ca0b0") ; overlay0
      (border-strong "#7c7f93") ; overlay2
      (decorator     "#acb0be") ; surface2

      ;; ── Syntax / semantic — Modus role taxonomy, painted with Latte ──
      (syn-keyword   "#8839ef") ; mauve
      (syn-string    "#40a02b") ; green
      (syn-number    "#209fb5") ; sapphire
      (syn-function  "#1e66f5") ; blue
      (syn-builtin   "#ea76cb") ; pink
      (syn-type      "#179299") ; teal
      (syn-variable  "#04a5e5") ; sky
      (syn-tag       "#179299") ; alias of type
      (syn-comment   "#8c8fa1") ; overlay1
      (syn-docstring "#618833") ; muted green (manual)
      ;; Semantic status — Catppuccin red/yellow/green/blue
      (err  "#d20f39")
      (warn "#df8e1d")
      (ok   "#40a02b")
      (info "#1e66f5"))

  (custom-theme-set-faces
   'jylhis-catppuccin-latte

   ;; ─────────────────────────────────────────────
   ;; Frame / base
   ;; ─────────────────────────────────────────────
   `(default             ((,class :background ,bg :foreground ,fg)))
   `(cursor              ((,class :background ,accent)))
   `(fringe              ((,class :background ,bg)))
   `(vertical-border     ((,class :foreground ,border)))
   `(window-divider      ((,class :foreground ,border)))
   `(window-divider-first-pixel  ((,class :foreground ,border)))
   `(window-divider-last-pixel   ((,class :foreground ,border)))
   `(shadow              ((,class :foreground ,fg-faint)))

   ;; ─────────────────────────────────────────────
   ;; Text emphasis
   ;; ─────────────────────────────────────────────
   `(bold                ((,class :weight bold :foreground ,fg-heading)))
   `(italic              ((,class :slant italic)))
   `(underline           ((,class :underline (:color ,fg-muted))))
   `(link                ((,class :foreground ,accent :underline (:color ,accent))))
   `(link-visited        ((,class :foreground ,syn-number :underline (:color ,syn-number))))

   ;; ─────────────────────────────────────────────
   ;; Selection + region  (KEYBOARD.md primitives)
   ;; ─────────────────────────────────────────────
   `(region              ((,class :background ,accent-subtle :extend t)))
   `(secondary-selection ((,class :background ,surface :extend t)))
   `(highlight           ((,class :background ,surface-raised :extend t)))
   `(hl-line             ((,class :background ,bg-subtle :extend t)))
   `(match               ((,class :background ,accent-subtle :foreground ,accent :weight bold)))
   `(isearch             ((,class :background ,accent :foreground ,bg :weight bold)))
   `(isearch-fail        ((,class :background ,err :foreground ,bg)))
   `(lazy-highlight      ((,class :background ,accent-subtle :foreground ,fg)))

   ;; ─────────────────────────────────────────────
   ;; Mode line
   ;; ─────────────────────────────────────────────
   `(mode-line
     ((,class :background ,surface :foreground ,fg
              :box (:line-width 3 :color ,surface))))
   `(mode-line-inactive
     ((,class :background ,bg-subtle :foreground ,fg-muted
              :box (:line-width 3 :color ,bg-subtle))))
   `(mode-line-highlight ((,class :foreground ,accent :background ,surface-raised)))
   `(mode-line-emphasis  ((,class :foreground ,accent :weight bold)))
   `(mode-line-buffer-id ((,class :foreground ,fg-heading :weight bold)))

   ;; doom-modeline
   `(doom-modeline-bar              ((,class :background ,accent)))
   `(doom-modeline-bar-inactive     ((,class :background ,surface)))
   `(doom-modeline-buffer-file      ((,class :foreground ,fg-heading :weight bold)))
   `(doom-modeline-buffer-modified  ((,class :foreground ,warn :weight bold)))
   `(doom-modeline-buffer-major-mode ((,class :foreground ,syn-tag :weight bold)))
   `(doom-modeline-project-dir      ((,class :foreground ,fg-muted)))
   `(doom-modeline-info             ((,class :foreground ,ok)))
   `(doom-modeline-warning          ((,class :foreground ,warn)))
   `(doom-modeline-urgent           ((,class :foreground ,err)))
   `(doom-modeline-lsp-success      ((,class :foreground ,ok)))
   `(doom-modeline-lsp-warning      ((,class :foreground ,warn)))
   `(doom-modeline-lsp-error        ((,class :foreground ,err)))

   ;; Header-line = the "second toolbar". Kept quiet.
   `(header-line          ((,class :background ,bg-subtle :foreground ,fg-muted
                                   :box (:line-width 3 :color ,bg-subtle))))

   ;; Tab-bar / tab-line — selected tab uses the canonical language
   `(tab-bar              ((,class :background ,bg-subtle :foreground ,fg-muted)))
   `(tab-bar-tab          ((,class :background ,surface :foreground ,fg
                                   :box (:line-width 3 :color ,surface)
                                   :weight bold)))
   `(tab-bar-tab-inactive ((,class :background ,bg-subtle :foreground ,fg-muted
                                   :box (:line-width 3 :color ,bg-subtle))))

   ;; ─────────────────────────────────────────────
   ;; Minibuffer / echo area
   ;; ─────────────────────────────────────────────
   `(minibuffer-prompt    ((,class :foreground ,accent :weight bold)))
   `(error                ((,class :foreground ,err   :weight bold)))
   `(warning              ((,class :foreground ,warn  :weight bold)))
   `(success              ((,class :foreground ,ok    :weight bold)))

   ;; ─────────────────────────────────────────────
   ;; Font-lock  (semantic face mapping)
   ;; ─────────────────────────────────────────────
   `(font-lock-builtin-face          ((,class :foreground ,syn-builtin)))
   `(font-lock-comment-face          ((,class :foreground ,syn-comment :slant italic)))
   `(font-lock-comment-delimiter-face ((,class :foreground ,syn-comment)))
   `(font-lock-constant-face         ((,class :foreground ,syn-number)))
   `(font-lock-doc-face              ((,class :foreground ,syn-docstring :slant italic)))
   `(font-lock-function-name-face    ((,class :foreground ,syn-function :weight bold)))
   `(font-lock-keyword-face          ((,class :foreground ,syn-keyword :weight bold)))
   `(font-lock-negation-char-face    ((,class :foreground ,err)))
   `(font-lock-preprocessor-face     ((,class :foreground ,syn-builtin)))
   `(font-lock-regexp-grouping-backslash ((,class :foreground ,syn-function :weight bold)))
   `(font-lock-regexp-grouping-construct ((,class :foreground ,syn-keyword :weight bold)))
   `(font-lock-string-face           ((,class :foreground ,syn-string)))
   `(font-lock-type-face             ((,class :foreground ,syn-type)))
   `(font-lock-variable-name-face    ((,class :foreground ,syn-variable)))
   `(font-lock-warning-face          ((,class :foreground ,warn :weight bold)))

   ;; Tree-sitter richer faces (Emacs 29+)
   `(font-lock-bracket-face          ((,class :foreground ,fg-muted)))
   `(font-lock-delimiter-face        ((,class :foreground ,fg-muted)))
   `(font-lock-escape-face           ((,class :foreground ,syn-function)))
   `(font-lock-misc-punctuation-face ((,class :foreground ,fg-muted)))
   `(font-lock-number-face           ((,class :foreground ,syn-number)))
   `(font-lock-operator-face         ((,class :foreground ,syn-keyword)))
   `(font-lock-property-name-face    ((,class :foreground ,syn-tag)))
   `(font-lock-property-use-face     ((,class :foreground ,syn-tag)))
   `(font-lock-punctuation-face      ((,class :foreground ,fg-muted)))

   ;; ─────────────────────────────────────────────
   ;; Line numbers
   ;; ─────────────────────────────────────────────
   `(line-number              ((,class :background ,bg :foreground ,fg-faint)))
   `(line-number-current-line ((,class :background ,bg-subtle :foreground ,accent :weight bold)))
   `(line-number-major-tick   ((,class :foreground ,fg-muted)))
   `(line-number-minor-tick   ((,class :foreground ,fg-faint)))

   ;; ─────────────────────────────────────────────
   ;; Parens / structure
   ;; ─────────────────────────────────────────────
   `(show-paren-match         ((,class :background ,accent-subtle :foreground ,accent :weight bold)))
   `(show-paren-mismatch      ((,class :background ,err :foreground ,bg :weight bold)))

   ;; rainbow-delimiters
   `(rainbow-delimiters-depth-1-face ((,class :foreground ,syn-keyword)))
   `(rainbow-delimiters-depth-2-face ((,class :foreground ,syn-string)))
   `(rainbow-delimiters-depth-3-face ((,class :foreground ,syn-tag)))
   `(rainbow-delimiters-depth-4-face ((,class :foreground ,syn-number)))
   `(rainbow-delimiters-depth-5-face ((,class :foreground ,syn-function)))
   `(rainbow-delimiters-depth-6-face ((,class :foreground ,accent)))
   `(rainbow-delimiters-depth-7-face ((,class :foreground ,fg-muted)))
   `(rainbow-delimiters-unmatched-face ((,class :foreground ,err :weight bold)))

   ;; ─────────────────────────────────────────────
   ;; Vertico / Consult / Marginalia / Corfu / Orderless
   ;; — this IS the command palette (KEYBOARD.md §"Command palette")
   ;; ─────────────────────────────────────────────
   `(vertico-current        ((,class :background ,accent-subtle
                                     :foreground ,fg :extend t
                                     :weight normal)))
   `(vertico-group-title    ((,class :foreground ,fg-faint :slant italic)))
   `(vertico-group-separator ((,class :foreground ,decorator :strike-through t)))

   `(marginalia-key          ((,class :foreground ,accent :weight bold)))
   `(marginalia-documentation ((,class :foreground ,fg-muted :slant italic)))
   `(marginalia-date         ((,class :foreground ,syn-number)))
   `(marginalia-file-name    ((,class :foreground ,fg)))
   `(marginalia-size         ((,class :foreground ,fg-muted)))
   `(marginalia-mode         ((,class :foreground ,syn-tag)))
   `(marginalia-function     ((,class :foreground ,syn-function)))
   `(marginalia-type         ((,class :foreground ,syn-tag)))
   `(marginalia-null         ((,class :foreground ,fg-faint)))
   `(marginalia-value        ((,class :foreground ,fg)))

   `(consult-file           ((,class :foreground ,fg)))
   `(consult-bookmark       ((,class :foreground ,syn-number)))
   `(consult-line-number    ((,class :foreground ,fg-faint)))
   `(consult-preview-line   ((,class :background ,bg-subtle :extend t)))
   `(consult-preview-match  ((,class :background ,accent-subtle :foreground ,accent)))

   `(orderless-match-face-0  ((,class :foreground ,accent :weight bold)))
   `(orderless-match-face-1  ((,class :foreground ,syn-string :weight bold)))
   `(orderless-match-face-2  ((,class :foreground ,syn-tag :weight bold)))
   `(orderless-match-face-3  ((,class :foreground ,syn-number :weight bold)))

   `(corfu-default           ((,class :background ,surface-raised :foreground ,fg)))
   `(corfu-current           ((,class :background ,accent-subtle :foreground ,fg)))
   `(corfu-border            ((,class :background ,border-strong)))
   `(corfu-bar               ((,class :background ,accent)))
   `(corfu-echo              ((,class :foreground ,fg-muted :slant italic)))

   ;; Eldoc / tooltip
   `(eldoc-highlight-function-argument ((,class :foreground ,accent :weight bold)))
   `(tooltip                 ((,class :background ,surface-raised :foreground ,fg
                                      :inherit variable-pitch)))

   ;; which-key — the leader cheatsheet (KEYBOARD.md §"Leader key cheatsheet")
   `(which-key-key-face        ((,class :foreground ,accent :weight bold)))
   `(which-key-group-description-face ((,class :foreground ,syn-tag)))
   `(which-key-command-description-face ((,class :foreground ,fg)))
   `(which-key-local-map-description-face ((,class :foreground ,syn-string)))
   `(which-key-separator-face  ((,class :foreground ,decorator)))
   `(which-key-note-face       ((,class :foreground ,fg-faint)))

   ;; ─────────────────────────────────────────────
   ;; Org
   ;; ─────────────────────────────────────────────
   `(org-level-1    ((,class :foreground ,accent       :weight bold :height 1.4)))
   `(org-level-2    ((,class :foreground ,syn-tag      :weight bold :height 1.2)))
   `(org-level-3    ((,class :foreground ,syn-string   :weight bold :height 1.1)))
   `(org-level-4    ((,class :foreground ,syn-number   :weight bold)))
   `(org-level-5    ((,class :foreground ,syn-function :weight bold)))
   `(org-level-6    ((,class :foreground ,syn-keyword)))
   `(org-level-7    ((,class :foreground ,fg-muted)))
   `(org-level-8    ((,class :foreground ,fg-faint)))

   `(org-document-title      ((,class :foreground ,fg-heading :weight bold :height 1.6)))
   `(org-document-info       ((,class :foreground ,fg-muted)))
   `(org-document-info-keyword ((,class :foreground ,fg-faint)))
   `(org-meta-line           ((,class :foreground ,fg-faint :slant italic)))
   `(org-drawer              ((,class :foreground ,fg-faint)))
   `(org-special-keyword     ((,class :foreground ,syn-tag)))

   `(org-todo                ((,class :foreground ,warn :weight bold :box (:line-width 1 :color ,warn))))
   `(org-done                ((,class :foreground ,ok :weight bold :box (:line-width 1 :color ,ok))))
   `(org-headline-done       ((,class :foreground ,fg-muted :strike-through nil)))

   `(org-date                ((,class :foreground ,syn-number :underline nil)))
   `(org-tag                 ((,class :foreground ,fg-muted :weight normal)))
   `(org-priority            ((,class :foreground ,accent :weight bold)))

   `(org-block               ((,class :background ,bg-subtle :extend t)))
   `(org-block-begin-line    ((,class :background ,bg-subtle :foreground ,fg-faint :extend t)))
   `(org-block-end-line      ((,class :background ,bg-subtle :foreground ,fg-faint :extend t)))
   `(org-code                ((,class :foreground ,syn-string :background ,bg-subtle)))
   `(org-verbatim            ((,class :foreground ,syn-string)))
   `(org-quote               ((,class :foreground ,fg-muted :slant italic)))

   `(org-table               ((,class :foreground ,fg :background ,bg-subtle)))
   `(org-table-header        ((,class :foreground ,fg-heading :background ,surface :weight bold)))

   `(org-link                ((,class :inherit link)))
   `(org-footnote            ((,class :foreground ,syn-number :underline t)))
   `(org-ellipsis            ((,class :foreground ,fg-faint :underline nil)))
   `(org-hide                ((,class :foreground ,bg)))

   ;; org-modern helpers
   `(org-modern-tag          ((,class :foreground ,bg :background ,syn-tag :weight bold)))
   `(org-modern-date-active  ((,class :foreground ,bg :background ,accent :weight bold)))

   ;; Agenda
   `(org-agenda-structure    ((,class :foreground ,accent :weight bold)))
   `(org-agenda-date         ((,class :foreground ,syn-tag :weight bold)))
   `(org-agenda-date-today   ((,class :foreground ,accent :weight bold :underline t)))
   `(org-agenda-date-weekend ((,class :foreground ,fg-muted)))
   `(org-scheduled           ((,class :foreground ,syn-string)))
   `(org-scheduled-today     ((,class :foreground ,ok :weight bold)))
   `(org-scheduled-previously ((,class :foreground ,warn)))
   `(org-upcoming-deadline   ((,class :foreground ,warn)))
   `(org-warning             ((,class :foreground ,warn :weight bold)))

   ;; ─────────────────────────────────────────────
   ;; Dired
   ;; ─────────────────────────────────────────────
   `(dired-directory         ((,class :foreground ,syn-tag :weight bold)))
   `(dired-symlink           ((,class :foreground ,info)))
   `(dired-broken-symlink    ((,class :foreground ,err :strike-through t)))
   `(dired-header            ((,class :foreground ,accent :weight bold)))
   `(dired-mark              ((,class :foreground ,accent)))
   `(dired-marked            ((,class :background ,accent-subtle :foreground ,accent :weight bold)))
   `(dired-perm-write        ((,class :foreground ,warn)))
   `(dired-flagged           ((,class :foreground ,err :weight bold)))
   `(dired-ignored           ((,class :foreground ,fg-faint)))

   ;; ─────────────────────────────────────────────
   ;; Magit / diff
   ;; ─────────────────────────────────────────────
   `(diff-added              ((,class :background ,bg-subtle :foreground ,ok)))
   `(diff-removed            ((,class :background ,bg-subtle :foreground ,err)))
   `(diff-context            ((,class :foreground ,fg-muted)))
   `(diff-hunk-header        ((,class :background ,surface :foreground ,fg-heading :weight bold)))
   `(diff-file-header        ((,class :background ,surface :foreground ,accent :weight bold)))
   `(diff-refine-added       ((,class :background ,accent-subtle :foreground ,ok :weight bold)))
   `(diff-refine-removed     ((,class :background ,accent-subtle :foreground ,err :weight bold)))

   `(magit-section-heading           ((,class :foreground ,accent :weight bold)))
   `(magit-section-highlight         ((,class :background ,bg-subtle :extend t)))
   `(magit-branch-local              ((,class :foreground ,syn-tag :weight bold)))
   `(magit-branch-remote             ((,class :foreground ,syn-string :weight bold)))
   `(magit-branch-current            ((,class :foreground ,accent :weight bold
                                              :box (:line-width 1 :color ,accent))))
   `(magit-tag                       ((,class :foreground ,syn-number)))
   `(magit-hash                      ((,class :foreground ,fg-faint)))
   `(magit-log-author                ((,class :foreground ,syn-function)))
   `(magit-log-date                  ((,class :foreground ,fg-faint)))
   `(magit-diff-added                ((,class :background ,bg-subtle :foreground ,ok)))
   `(magit-diff-added-highlight      ((,class :background ,surface :foreground ,ok)))
   `(magit-diff-removed              ((,class :background ,bg-subtle :foreground ,err)))
   `(magit-diff-removed-highlight    ((,class :background ,surface :foreground ,err)))
   `(magit-diff-context              ((,class :foreground ,fg-muted)))
   `(magit-diff-context-highlight    ((,class :background ,bg-subtle :foreground ,fg)))
   `(magit-diff-hunk-heading         ((,class :background ,surface :foreground ,fg-heading)))
   `(magit-diff-hunk-heading-highlight ((,class :background ,surface-raised :foreground ,fg-heading :weight bold)))
   `(magit-diffstat-added            ((,class :foreground ,ok)))
   `(magit-diffstat-removed          ((,class :foreground ,err)))

   ;; ─────────────────────────────────────────────
   ;; Flymake / Flycheck
   ;; ─────────────────────────────────────────────
   `(flymake-error           ((,class :underline (:style wave :color ,err))))
   `(flymake-warning         ((,class :underline (:style wave :color ,warn))))
   `(flymake-note            ((,class :underline (:style wave :color ,info))))
   `(flycheck-error          ((,class :underline (:style wave :color ,err))))
   `(flycheck-warning        ((,class :underline (:style wave :color ,warn))))
   `(flycheck-info           ((,class :underline (:style wave :color ,info))))
   `(compilation-error       ((,class :foreground ,err :weight bold)))
   `(compilation-warning     ((,class :foreground ,warn :weight bold)))
   `(compilation-info        ((,class :foreground ,info)))

   ;; ─────────────────────────────────────────────
   ;; Company + Eglot
   ;; ─────────────────────────────────────────────
   `(company-tooltip                      ((,class :background ,surface-raised :foreground ,fg)))
   `(company-tooltip-selection            ((,class :background ,accent-subtle :foreground ,fg)))
   `(company-tooltip-common               ((,class :foreground ,accent :weight bold)))
   `(company-tooltip-annotation           ((,class :foreground ,fg-muted)))
   `(company-scrollbar-bg                 ((,class :background ,surface)))
   `(company-scrollbar-fg                 ((,class :background ,border-strong)))

   `(eglot-highlight-symbol-face          ((,class :background ,surface :weight bold)))
   `(eglot-mode-line                      ((,class :foreground ,accent)))
   `(eglot-diagnostic-tag-deprecated-face ((,class :strike-through t :foreground ,fg-faint)))

   ;; ─────────────────────────────────────────────
   ;; Terminal (vterm / ansi-term)  — Catppuccin Latte ANSI
   ;; Bright-yellow is intentionally overridden to brand peach (Jylhis rule).
   ;; ─────────────────────────────────────────────
   `(ansi-color-black               ((,class :foreground "#4c4f69" :background "#4c4f69")))
   `(ansi-color-red                 ((,class :foreground "#d20f39" :background "#d20f39")))
   `(ansi-color-green               ((,class :foreground "#40a02b" :background "#40a02b")))
   `(ansi-color-yellow              ((,class :foreground "#df8e1d" :background "#df8e1d")))
   `(ansi-color-blue                ((,class :foreground "#1e66f5" :background "#1e66f5")))
   `(ansi-color-magenta             ((,class :foreground "#ea76cb" :background "#ea76cb")))
   `(ansi-color-cyan                ((,class :foreground "#179299" :background "#179299")))
   `(ansi-color-white               ((,class :foreground "#5c5f77" :background "#5c5f77")))
   `(ansi-color-bright-black        ((,class :foreground "#6c6f85" :background "#6c6f85")))
   `(ansi-color-bright-red          ((,class :foreground "#e64553" :background "#e64553")))
   `(ansi-color-bright-green        ((,class :foreground "#618833" :background "#618833")))
   `(ansi-color-bright-yellow       ((,class :foreground "#fe640b" :background "#fe640b")))
   `(ansi-color-bright-blue         ((,class :foreground "#209fb5" :background "#209fb5")))
   `(ansi-color-bright-magenta      ((,class :foreground "#8839ef" :background "#8839ef")))
   `(ansi-color-bright-cyan         ((,class :foreground "#04a5e5" :background "#04a5e5")))
   `(ansi-color-bright-white        ((,class :foreground "#4c4f69" :background "#4c4f69")))

   ;; ─────────────────────────────────────────────
   ;; Misc
   ;; ─────────────────────────────────────────────
   `(trailing-whitespace       ((,class :background ,err)))
   `(whitespace-tab            ((,class :foreground ,fg-faint)))
   `(whitespace-space          ((,class :foreground ,fg-faint)))
   `(whitespace-newline        ((,class :foreground ,fg-faint)))
   `(whitespace-indentation    ((,class :foreground ,fg-faint)))
   `(whitespace-line           ((,class :background ,bg-subtle)))
   `(whitespace-trailing       ((,class :background ,err)))

   `(hi-yellow                 ((,class :background ,warn :foreground ,bg)))
   `(hi-pink                   ((,class :background ,syn-number :foreground ,bg)))
   `(hi-green                  ((,class :background ,ok :foreground ,bg)))

   ;; tab-line / centaur-tabs
   `(tab-line-tab-current      ((,class :background ,surface :foreground ,accent :weight bold)))
   `(tab-line-tab              ((,class :background ,bg-subtle :foreground ,fg-muted)))

   ;; hl-todo
   `(hl-todo                   ((,class :foreground ,warn :weight bold)))

   ;; indent-bars
   `(indent-bars-face          ((,class :foreground ,fg-faint)))))

(custom-theme-set-variables
 'jylhis-catppuccin-latte
 '(ansi-color-names-vector
   ["#4c4f69" "#d20f39" "#40a02b" "#df8e1d"
    "#1e66f5" "#ea76cb" "#179299" "#5c5f77"])
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(hl-todo-keyword-faces
   '(("FIXME"      . "#d20f39")
     ("BUG"        . "#d20f39")
     ("TODO"       . "#df8e1d")
     ("HACK"       . "#df8e1d")
     ("NOTE"       . "#1e66f5")
     ("REVIEW"     . "#1e66f5")
     ("DEPRECATED" . "#7c7f93"))))

(provide-theme 'jylhis-catppuccin-latte)

;;;###autoload
(and load-file-name
     (boundp 'custom-theme-load-path)
     (add-to-list 'custom-theme-load-path
                  (file-name-as-directory
                   (file-name-directory load-file-name))))

;;; jylhis-catppuccin-latte-theme.el ends here
